routes/web.php
<?php

use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\PageController::class, 'finalizado']);

/*Route::get("/", function () {
    return view("welcome");
});

Auth::routes(['verify' => true]);
*/
Route::controller(App\Http\Controllers\PageController::class)->group(
    function () {
        //Route::get("/home", "home")->name("home");
        Route::get("/centros-de-canje", "centros")->name("centros");
        //Route::get("/preguntas-frecuentes", "preguntas")->name("preguntas");
        //Route::get("/mecanica", "mecanica")->name("mecanica");
        Route::get("/bases", "bases")->name("bases");
        //Route::get("/mis-premios", "misPremios")->name("mispremios")->middleware(['auth', 'verified']);
    }
);
/*
Route::controller(App\Http\Controllers\PremioController::class)->group(
    function () {
        Route::get("/premios", "create")->name("premios");
        Route::post("/premios", "store")->name("premios")->middleware(['auth', 'verified']);
    }
);*/

app/Models/Folio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Folio extends Model
{
    use HasFactory;

    protected $keyType = "string";
    protected $primaryKey = "codigo";
    public $incrementing = false;
    public $timestamps = false;
    protected $hidden = ["codigo", "corrida"];

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        "codigo",
        "corrida",
        "fecha_venta",
        "fecha_viaje",
        "participante_id",
        "created_at",
    ];

    public function premio()
    {
        return $this->hasOne(Premio::class, "folio_codigo", "codigo");
    }
    

    public function scopeUltimo($query)
    {
        return $query->orderBy("created_at", "desc");
    }

    public function participante()
    {
        return $this->belongsTo(Participante::class, "id");
    }

    public function getFechaAttribute()
    {
        $date = strtotime($this->created_at);
        $diassemana = [
            "Domingo",
            "Lunes",
            "Martes",
            "Miercoles",
            "Jueves",
            "Viernes",
            "Sábado",
        ];
        $meses = [
            "enero",
            "febrero",
            "marzo",
            "abril",
            "mayo",
            "junio",
            "julio",
            "agosto",
            "aeptiembre",
            "octubre",
            "noviembre",
            "diciembre",
        ];

        return $diassemana[date("w", $date)] .
            " " .
            date("d", $date) .
            " de " .
            $meses[date("n", $date) - 1] .
            " de " .
            date("Y - H:i", $date);
    }
}

resources/views/finalizado.blade.php
@extends('layouts.app')
@section('title')
Inicio
@endsection
@section('content')

<div class="mecanica" id="intro">
    <div class="intro">
        <div class="container">
            <div class="ultimo-registro">
                <strong>
                    @if(isset($ultimo))
                    Último registro: {{str_pad($ultimo->premio->id, 8, '0',STR_PAD_LEFT)}} {{$ultimo->fecha}} hrs.
                    @endif
                </strong>
                <div>
                    Este <span id="fecha_actual"></span> a las <span id="hora_actual"></span> seguro ganas.
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <img class="img-fluid" src="{{asset('img/banner.png?v=2')}}" alt="">
                </div>
            </div>
        </div>
    </div>
</div>

<component :is="'script'">
    var now = new Date('{{date(DATE_ATOM)}}') * 1;
    var segundos = 0;
    function actualizarFecha(){
        const meses = ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre',
        'noviembre', 'diciembre'];
        const dias_semana = ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'];
        const fecha = new Date(now + (segundos * 1000));
        document.getElementById('fecha_actual').innerText = dias_semana[fecha.getDay()] + ' ' + fecha.getDate() + ' de ' +
        meses[fecha.getMonth()] + ' de ' + fecha.getUTCFullYear();
        document.getElementById('hora_actual').innerText = fecha.getHours().toString().padStart(2, 0) + ':' + fecha.getMinutes().toString().padStart(2, 0)+':'+fecha.getSeconds().toString().padStart(2, 0);
        segundos += 1;
    }
    actualizarFecha();
    setInterval(actualizarFecha, 1000);
</component>
@endsection